# Максимально-допустимые длины строк
TAG_NAME_LENGTH = 32
TAG_SLUG_LENGTH = TAG_NAME_LENGTH
INGREDIENT_NAME_LENGTH = 128
INGREDIENT_MEASURE_LENGTH = 64
USERNAME_LENGTH = 150
EMAIL_LENGTH = 254
NAME_MAX_LENGTH = 256

SCORE_MIN = 1
SCORE_MAX = 10
