# Generated by Django 5.2.5 on 2025-08-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeingredient",
            name="quantity",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                max_length=32, null=True, unique=True, verbose_name="Слаг"
            ),
        ),
    ]
