# Generated by Django 5.2.5 on 2025-08-14 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipeingredient_quantity_alter_tag_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipeingredient",
            old_name="quantity",
            new_name="amount",
        ),
    ]
